# These are supported funding model platforms

github: [rvrheenen]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
liberapay: rvrheenen # Replace with a single Liberapay username
custom: paypal.me/rivartech # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
